src/Entity/Visiteur.php
<?php

namespace App\Entity;

use App\Repository\VisiteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: VisiteurRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Visiteur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var ?string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nomVisiteur = null;

    #[ORM\Column(length: 255)]
    private ?string $prenomVisiteur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adVisiteur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $villeVisiteur = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $telVisiteur = null;

    #[ORM\Column(length: 6)]
    private ?string $CpVisiteur = null;

    #[ORM\OneToMany(mappedBy: 'visiteur', targetEntity: Ticket::class)]
    private Collection $ticket;

    public function __construct()
    {
        $this->ticket = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNomVisiteur(): ?string
    {
        return $this->nomVisiteur;
    }

    public function setNomVisiteur(string $nomVisiteur): static
    {
        $this->nomVisiteur = $nomVisiteur;

        return $this;
    }

    public function getPrenomVisiteur(): ?string
    {
        return $this->prenomVisiteur;
    }

    public function setPrenomVisiteur(string $prenomVisiteur): static
    {
        $this->prenomVisiteur = $prenomVisiteur;

        return $this;
    }

    public function getAdVisiteur(): ?string
    {
        return $this->adVisiteur;
    }

    public function setAdVisiteur(?string $adVisiteur): static
    {
        $this->adVisiteur = $adVisiteur;

        return $this;
    }

    public function getVilleVisiteur(): ?string
    {
        return $this->villeVisiteur;
    }

    public function setVilleVisiteur(?string $villeVisiteur): static
    {
        $this->villeVisiteur = $villeVisiteur;

        return $this;
    }

    public function getTelVisiteur(): ?string
    {
        return $this->telVisiteur;
    }

    public function setTelVisiteur(?string $telVisiteur): static
    {
        $this->telVisiteur = $telVisiteur;

        return $this;
    }

    public function getCpVisiteur(): ?string
    {
        return $this->CpVisiteur;
    }

    public function setCpVisiteur(?string $CpVisiteur): static
    {
        $this->CpVisiteur = $CpVisiteur;

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTicket(): Collection
    {
        return $this->ticket;
    }

    public function addTicket(Ticket $ticket): static
    {
        if (!$this->ticket->contains($ticket)) {
            $this->ticket->add($ticket);
            $ticket->setVisiteur($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): static
    {
        if ($this->ticket->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getVisiteur() === $this) {
                $ticket->setVisiteur(null);
            }
        }

        return $this;
    }
}

src/Controller/VisiteurController.php
<?php

namespace App\Controller;

use App\Entity\Visiteur;
use App\Repository\TicketRepository;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VisiteurController extends AbstractController
{
    #[Route('/visiteur/{id}', name: 'app_visiteur_show', requirements: ['id' => '\d+'])]
    public function show(#[MapEntity(expr: 'repository.findWithId(id)')] ?Visiteur $visiteur, TicketRepository $ticketRepository): Response
    {
        $currentUser = $this->getUser();

        if (is_null($visiteur)) {
            return $this->redirectToRoute('app_home', status: 303);
        }

        // Si l'utilisateur n'est pas connecté, redirigez-le vers la page de connexion
        if (!$currentUser) {
            return $this->redirectToRoute('app_login');
        }

        $userIdFromRoute = $visiteur->getId();

        if (in_array('ROLE_ADMIN', $currentUser->getRoles(), true) || $currentUser->getId() == $userIdFromRoute) {
            $usedTicket = $ticketRepository->findUsedByVisiteur($visiteur);
            $unusedTicket = $ticketRepository->findNotUsedByVisiteur($visiteur);

            return $this->render('visiteur/show.html.twig', [
                'visiteur' => $visiteur,
                'usedTicket' => $usedTicket,
                'unusedTicket' => $unusedTicket,
            ]);
        }

        return $this->redirectToRoute('app_home', status: 303);
    }
}

templates/visiteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ visiteur.prenomVisiteur }} {% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/css/style.css"/>
    <link href="{{ asset('css/visiteur.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}


    <div class="containerr">
        <div class="left" >
            <img class="img-visiteur" src="/img/3135715.png" alt="Visiteur">

        </div>
        <div class="right" >
            <ul class="info-visiteur" style="list-style-type:none;">

                <li class="info">Email : <b>{{ visiteur.email }}</b></li>
                <li class="info">Tel : <b>{{ visiteur.telVisiteur}}</b></li>
                <li class="info">Adresse : <b>{{ visiteur.adVisiteur }}</b></li>
                <li class="info">Ville : <b>{{ visiteur.villeVisiteur }}</b></li>
                <li class="info">CP : <b>{{ visiteur.cpVisiteur }}</b></li>
            </ul>
        </div>

    </div>
    <div class="ticket">
    {% if usedTicket is not empty or unusedTicket is not empty %}
            <div class="titre-ticket">
                <h2>Liste des tickets</h2>
            </div>
            <div class="info-ticket">
                {% set count = 0 %}
                {% if unusedTicket is not empty %}
                    <ul class="unused" style="list-style-type:none;">
                        <h3>Tickets à venir :</h3>
                        {% for ticket in unusedTicket %}
                            {% set count = count + 1 %}
                            <a href="{{ path('app_ticket_show', {id: ticket.id}) }}">
                                <li><h3>Ticket N°{{ count }}</h3></li>
                            </a>
                                <li><h3>Date : {{ ticket.dateTicket | date('d/m/Y') }}</h3></li>
                            <br>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if usedTicket is not empty %}
                    <ul class="used" style="list-style-type:none;">
                        <h3>Tickets passés :</h3>
                        {% for ticket in usedTicket %}
                            {% set count = count + 1 %}
                            <a href="{{ path('app_ticket_show', {id: ticket.id}) }}">
                                <li><h3>Ticket N°{{ count }}</h3></li>
                            </a>
                            <li><h3>Date : {{ ticket.dateTicket | date('d/m/Y') }}</h3></li>
                            <br>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
    {% endif %}
        <div class="button">
            <a href="{{ path('app_ticket_precreate') }}" class="btn btn-success w-75 p-3">Créer un ticket</a>
        </div>
    </div>


{% endblock %}